name: Check vCPU on BuildJet

on: push

jobs:
  check_cpu:
    runs-on: buildjet-8vcpu-ubuntu-2004 # Ganti dengan runner BuildJet yang ingin Anda cek

    steps:
    - name: Checkout code
      uses: actions/cache@v3

    - name: Run
      run: |
        lscpu
        
